### ISSUE TITLE
Follow Me not showing icons

### ISSUE THREAD

**Issue by christianh814** [miguelsimoni/hugo-initio#47]
Working on a website and the "Follow Me" Social icons are not showing up"

```toml

[[params.social]]
    title = 'twitter'
    url = 'https://twitter.com/MiaSanHollywood'
    icon = 'fab fa-twitter-square'
    footer = true
    sharethis = true
    network = 'twitter'

[[params.social]]
    title = 'instagram'
    url = 'https://www.instagram.com/miasanhollywood/'
    icon = 'fab fa-instagram'
    footer = true
    sharethis = true
    network = ''
```

However the site shows this...
<img width="225" alt="Screen Shot 2021-12-28 at 1 18 32 PM" src="https://user-images.githubusercontent.com/10502863/147607827-8b74573d-17c6-4c44-ac8d-d2d9034889ea.png">

No errors when I run `hugo server`

```shell
$ hugo server
Start building sites …
hugo v0.91.2+extended darwin/amd64 BuildDate=unknown

                   | EN
-------------------+-----
  Pages            |  9
  Paginator pages  |  0
  Non-page files   |  3
  Static files     |  9
  Processed images |  0
  Aliases          |  3
  Sitemaps         |  1
  Cleaned          |  0

Built in 19 ms
Watching for changes in /Users/chernand/git/msh-website/miasanhollywoodwebsite/{archetypes,content,package.json,themes}
Watching for config changes in /Users/chernand/git/msh-website/miasanhollywoodwebsite/config.toml
Environment: "development"
Serving pages from memory
Running in Fast Render Mode. For full rebuilds on change: hugo server --disableFastRender
Web Server is available at http://localhost:1313/ (bind address 127.0.0.1)
Press Ctrl+C to stop
```
